# Generated by Django 6.0.5 on 2026-05-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(choices=[('Palestra', 'Palestra'), ('Oficina', 'Oficina'), ('Mini Curso', 'Mini Curso'), ('Mesa Redonda', 'Mesa Redonda')], max_length=30)),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField()),
                ('local', models.CharField(max_length=255)),
                ('vagas', models.IntegerField()),
                ('carga_horaria', models.IntegerField()),
                ('responsavel', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Inscrições Abertas', 'Inscrições Abertas'), ('Encerrado', 'Encerrado')], default='Rascunho', max_length=30)),
            ],
        ),
    ]
